# Generated by Django 5.1.7 on 2025-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort_data', models.JSONField()),
                ('user_signature', models.TextField()),
                ('user_public_key', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('assigned_validator', models.CharField(blank=True, max_length=100, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
